# Generated by Django 3.2.14 on 2024-09-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_historicalpatient_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
