# Generated by Django 3.2.14 on 2024-09-14 23:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20240914_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientProxy',
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='state',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='country',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.address'),
        ),
    ]
