# Generated by Django 3.2.14 on 2024-09-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20240914_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line',
            field=models.CharField(blank=True, help_text='Comma-separated address lines', max_length=1000, null=True),
        ),
    ]
