import json

all_patients = {
    "resourceType": "Bundle",
    "id": "2f2f8fe6-ad90-4c27-8266-dbdaa7fa369e",
    "meta": {"lastUpdated": "2022-11-16T16:57:06.570+00:00"},
    "type": "searchset",
    "link": [
        {"relation": "self", "url": "http://localhost:8080/fhir/Patient"},
        {
            "relation": "next",
            "url": "http://localhost:8080/fhir?_getpages=2f2f8fe6-ad90-4c27-8266-dbdaa7fa369e&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset",
        },
    ],
    "entry": [
        {
            "fullUrl": "http://localhost:8080/fhir/Patient/4172",
            "resource": {
                "resourceType": "Patient",
                "id": "4172",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-10-26T17:59:39.534+00:00",
                    "source": "#U8mp7UmXjSsTPwER",
                    "profile": [
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
                    ],
                },
                "text": {
                    "status": "generated",
                    "div": '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: a4e5a1a\n .   Person seed: -2041434765497594412  Population seed: 12345</div>',
                },
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2106-3",
                                    "display": "White",
                                },
                            },
                            {"url": "text", "valueString": "White"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2186-5",
                                    "display": "Not Hispanic or Latino",
                                },
                            },
                            {"url": "text", "valueString": "Not Hispanic or Latino"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
                        "valueString": "Earlie274 Barton704",
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
                        "valueCode": "M",
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
                        "valueAddress": {
                            "city": "Marshfield",
                            "state": "Massachusetts",
                            "country": "US",
                        },
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
                        "valueDecimal": 0.0,
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
                        "valueDecimal": 9.0,
                    },
                ],
                "identifier": [
                    {
                        "system": "https://github.com/synthetichealth/synthea",
                        "value": "f6aae6ae-c382-593c-1330-6d6598282031",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "MR",
                                    "display": "Medical Record Number",
                                }
                            ],
                            "text": "Medical Record Number",
                        },
                        "system": "http://hospital.smarthealthit.org",
                        "value": "f6aae6ae-c382-593c-1330-6d6598282031",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "SS",
                                    "display": "Social Security Number",
                                }
                            ],
                            "text": "Social Security Number",
                        },
                        "system": "http://hl7.org/fhir/sid/us-ssn",
                        "value": "999-56-1370",
                    },
                ],
                "name": [
                    {
                        "use": "official",
                        "family": "Dickinson688",
                        "given": ["Brock407", "Bret7"],
                    }
                ],
                "telecom": [
                    {"system": "phone", "value": "555-385-9019", "use": "home"}
                ],
                "gender": "male",
                "birthDate": "2012-06-10",
                "address": [
                    {
                        "extension": [
                            {
                                "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                                "extension": [
                                    {
                                        "url": "latitude",
                                        "valueDecimal": 42.459178010105404,
                                    },
                                    {
                                        "url": "longitude",
                                        "valueDecimal": -71.20555483378946,
                                    },
                                ],
                            }
                        ],
                        "line": ["370 Auer Knoll"],
                        "city": "Arlington",
                        "state": "MA",
                        "postalCode": "02476",
                        "country": "US",
                    }
                ],
                "maritalStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                            "code": "S",
                            "display": "Never Married",
                        }
                    ],
                    "text": "Never Married",
                },
                "multipleBirthBoolean": False,
                "communication": [
                    {
                        "language": {
                            "coding": [
                                {
                                    "system": "urn:ietf:bcp:47",
                                    "code": "en-US",
                                    "display": "English",
                                }
                            ],
                            "text": "English",
                        }
                    }
                ],
            },
            "search": {"mode": "match"},
        },
        {
            "fullUrl": "http://localhost:8080/fhir/Patient/4599",
            "resource": {
                "resourceType": "Patient",
                "id": "4599",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-10-26T17:59:52.051+00:00",
                    "source": "#gFOYFQ6VYsMRR2ra",
                    "profile": [
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
                    ],
                },
                "text": {
                    "status": "generated",
                    "div": '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: a4e5a1a\n .   Person seed: -3500614978637125381  Population seed: 12345</div>',
                },
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2106-3",
                                    "display": "White",
                                },
                            },
                            {"url": "text", "valueString": "White"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2186-5",
                                    "display": "Not Hispanic or Latino",
                                },
                            },
                            {"url": "text", "valueString": "Not Hispanic or Latino"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
                        "valueString": "Miss492 Klein929",
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
                        "valueCode": "F",
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
                        "valueAddress": {
                            "city": "Marlborough",
                            "state": "Massachusetts",
                            "country": "US",
                        },
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
                        "valueDecimal": 0.0,
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
                        "valueDecimal": 8.0,
                    },
                ],
                "identifier": [
                    {
                        "system": "https://github.com/synthetichealth/synthea",
                        "value": "d92132ce-06ac-3ab4-217f-97257a290b22",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "MR",
                                    "display": "Medical Record Number",
                                }
                            ],
                            "text": "Medical Record Number",
                        },
                        "system": "http://hospital.smarthealthit.org",
                        "value": "d92132ce-06ac-3ab4-217f-97257a290b22",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "SS",
                                    "display": "Social Security Number",
                                }
                            ],
                            "text": "Social Security Number",
                        },
                        "system": "http://hl7.org/fhir/sid/us-ssn",
                        "value": "999-65-7810",
                    },
                ],
                "name": [
                    {
                        "use": "official",
                        "family": "Bauch723",
                        "given": ["Dannette613", "Darcie474"],
                    }
                ],
                "telecom": [
                    {"system": "phone", "value": "555-963-5669", "use": "home"}
                ],
                "gender": "female",
                "birthDate": "2013-07-04",
                "address": [
                    {
                        "extension": [
                            {
                                "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                                "extension": [
                                    {
                                        "url": "latitude",
                                        "valueDecimal": 42.80410279196755,
                                    },
                                    {
                                        "url": "longitude",
                                        "valueDecimal": -70.82470883225064,
                                    },
                                ],
                            }
                        ],
                        "line": ["593 Doyle Ranch"],
                        "city": "Newbury",
                        "state": "MA",
                        "country": "US",
                    }
                ],
                "maritalStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                            "code": "S",
                            "display": "Never Married",
                        }
                    ],
                    "text": "Never Married",
                },
                "multipleBirthBoolean": False,
                "communication": [
                    {
                        "language": {
                            "coding": [
                                {
                                    "system": "urn:ietf:bcp:47",
                                    "code": "en-US",
                                    "display": "English",
                                }
                            ],
                            "text": "English",
                        }
                    }
                ],
            },
            "search": {"mode": "match"},
        },
        {
            "fullUrl": "http://localhost:8080/fhir/Patient/4986",
            "resource": {
                "resourceType": "Patient",
                "id": "4986",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-10-26T18:00:11.231+00:00",
                    "source": "#gCOrHNMDMM0gQNnI",
                    "profile": [
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
                    ],
                },
                "text": {
                    "status": "generated",
                    "div": '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: a4e5a1a\n .   Person seed: -983629553680906212  Population seed: 12345</div>',
                },
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2106-3",
                                    "display": "White",
                                },
                            },
                            {"url": "text", "valueString": "White"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2186-5",
                                    "display": "Not Hispanic or Latino",
                                },
                            },
                            {"url": "text", "valueString": "Not Hispanic or Latino"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
                        "valueString": "Shemeka786 Schulist381",
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
                        "valueCode": "M",
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
                        "valueAddress": {
                            "city": "Methuen",
                            "state": "Massachusetts",
                            "country": "US",
                        },
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
                        "valueDecimal": 0.0,
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
                        "valueDecimal": 3.0,
                    },
                ],
                "identifier": [
                    {
                        "system": "https://github.com/synthetichealth/synthea",
                        "value": "db8bf256-3b32-250e-1a64-462236a64289",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "MR",
                                    "display": "Medical Record Number",
                                }
                            ],
                            "text": "Medical Record Number",
                        },
                        "system": "http://hospital.smarthealthit.org",
                        "value": "db8bf256-3b32-250e-1a64-462236a64289",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "SS",
                                    "display": "Social Security Number",
                                }
                            ],
                            "text": "Social Security Number",
                        },
                        "system": "http://hl7.org/fhir/sid/us-ssn",
                        "value": "999-75-9080",
                    },
                ],
                "name": [
                    {
                        "use": "official",
                        "family": "Predovic534",
                        "given": ["Kendall673"],
                    }
                ],
                "telecom": [
                    {"system": "phone", "value": "555-910-1361", "use": "home"}
                ],
                "gender": "male",
                "birthDate": "2018-12-29",
                "address": [
                    {
                        "extension": [
                            {
                                "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                                "extension": [
                                    {
                                        "url": "latitude",
                                        "valueDecimal": 42.05933702933904,
                                    },
                                    {
                                        "url": "longitude",
                                        "valueDecimal": -71.23107100887978,
                                    },
                                ],
                            }
                        ],
                        "line": ["698 Waters Mission"],
                        "city": "Foxborough",
                        "state": "MA",
                        "country": "US",
                    }
                ],
                "maritalStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                            "code": "S",
                            "display": "Never Married",
                        }
                    ],
                    "text": "Never Married",
                },
                "multipleBirthBoolean": False,
                "communication": [
                    {
                        "language": {
                            "coding": [
                                {
                                    "system": "urn:ietf:bcp:47",
                                    "code": "en-US",
                                    "display": "English",
                                }
                            ],
                            "text": "English",
                        }
                    }
                ],
            },
            "search": {"mode": "match"},
        },
        {
            "fullUrl": "http://localhost:8080/fhir/Patient/5224",
            "resource": {
                "resourceType": "Patient",
                "id": "5224",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-10-26T18:00:14.187+00:00",
                    "source": "#GUe15UdKjGJ4aS6v",
                    "profile": [
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
                    ],
                },
                "text": {
                    "status": "generated",
                    "div": '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: a4e5a1a\n .   Person seed: 8445145834301948876  Population seed: 12345</div>',
                },
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2106-3",
                                    "display": "White",
                                },
                            },
                            {"url": "text", "valueString": "White"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2186-5",
                                    "display": "Not Hispanic or Latino",
                                },
                            },
                            {"url": "text", "valueString": "Not Hispanic or Latino"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
                        "valueString": "Kendall673 Price929",
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
                        "valueCode": "M",
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
                        "valueAddress": {
                            "city": "Lynn",
                            "state": "Massachusetts",
                            "country": "US",
                        },
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
                        "valueDecimal": 0.0,
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
                        "valueDecimal": 6.0,
                    },
                ],
                "identifier": [
                    {
                        "system": "https://github.com/synthetichealth/synthea",
                        "value": "6ac91ddc-abeb-5435-9a52-382a1791f4cb",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "MR",
                                    "display": "Medical Record Number",
                                }
                            ],
                            "text": "Medical Record Number",
                        },
                        "system": "http://hospital.smarthealthit.org",
                        "value": "6ac91ddc-abeb-5435-9a52-382a1791f4cb",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "SS",
                                    "display": "Social Security Number",
                                }
                            ],
                            "text": "Social Security Number",
                        },
                        "system": "http://hl7.org/fhir/sid/us-ssn",
                        "value": "999-16-9135",
                    },
                ],
                "name": [
                    {"use": "official", "family": "Stracke611", "given": ["Mauro926"]}
                ],
                "telecom": [
                    {"system": "phone", "value": "555-878-1377", "use": "home"}
                ],
                "gender": "male",
                "birthDate": "2015-06-19",
                "address": [
                    {
                        "extension": [
                            {
                                "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                                "extension": [
                                    {
                                        "url": "latitude",
                                        "valueDecimal": 42.24523273249481,
                                    },
                                    {
                                        "url": "longitude",
                                        "valueDecimal": -71.87077545722823,
                                    },
                                ],
                            }
                        ],
                        "line": ["267 Stracke Annex"],
                        "city": "Worcester",
                        "state": "MA",
                        "postalCode": "01603",
                        "country": "US",
                    }
                ],
                "maritalStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                            "code": "S",
                            "display": "Never Married",
                        }
                    ],
                    "text": "Never Married",
                },
                "multipleBirthBoolean": False,
                "communication": [
                    {
                        "language": {
                            "coding": [
                                {
                                    "system": "urn:ietf:bcp:47",
                                    "code": "en-US",
                                    "display": "English",
                                }
                            ],
                            "text": "English",
                        }
                    }
                ],
            },
            "search": {"mode": "match"},
        },
        {
            "fullUrl": "http://localhost:8080/fhir/Patient/5580",
            "resource": {
                "resourceType": "Patient",
                "id": "5580",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-10-26T18:00:18.472+00:00",
                    "source": "#3l40qV2hwPuN6GO1",
                    "profile": [
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
                    ],
                },
                "text": {
                    "status": "generated",
                    "div": '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: a4e5a1a\n .   Person seed: 3278058205196319291  Population seed: 12345</div>',
                },
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2028-9",
                                    "display": "Asian",
                                },
                            },
                            {"url": "text", "valueString": "Asian"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2186-5",
                                    "display": "Not Hispanic or Latino",
                                },
                            },
                            {"url": "text", "valueString": "Not Hispanic or Latino"},
                        ],
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
                        "valueString": "Loreen513 Morissette863",
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
                        "valueCode": "F",
                    },
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
                        "valueAddress": {
                            "city": "Bourne",
                            "state": "Massachusetts",
                            "country": "US",
                        },
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
                        "valueDecimal": 0.0,
                    },
                    {
                        "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
                        "valueDecimal": 0.0,
                    },
                ],
                "identifier": [
                    {
                        "system": "https://github.com/synthetichealth/synthea",
                        "value": "a91945fc-e100-f2f9-3924-8c4c56aaf835",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "MR",
                                    "display": "Medical Record Number",
                                }
                            ],
                            "text": "Medical Record Number",
                        },
                        "system": "http://hospital.smarthealthit.org",
                        "value": "a91945fc-e100-f2f9-3924-8c4c56aaf835",
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "SS",
                                    "display": "Social Security Number",
                                }
                            ],
                            "text": "Social Security Number",
                        },
                        "system": "http://hl7.org/fhir/sid/us-ssn",
                        "value": "999-17-7034",
                    },
                ],
                "name": [
                    {
                        "use": "official",
                        "family": "Jones311",
                        "given": ["Merri201", "Ilse197"],
                    }
                ],
                "telecom": [
                    {"system": "phone", "value": "555-435-2798", "use": "home"}
                ],
                "gender": "female",
                "birthDate": "2022-07-21",
                "address": [
                    {
                        "extension": [
                            {
                                "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                                "extension": [
                                    {
                                        "url": "latitude",
                                        "valueDecimal": 42.29681116498799,
                                    },
                                    {
                                        "url": "longitude",
                                        "valueDecimal": -71.01059024781303,
                                    },
                                ],
                            }
                        ],
                        "line": ["407 Legros Passage"],
                        "city": "Quincy",
                        "state": "MA",
                        "postalCode": "02170",
                        "country": "US",
                    }
                ],
                "maritalStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                            "code": "S",
                            "display": "Never Married",
                        }
                    ],
                    "text": "Never Married",
                },
                "multipleBirthBoolean": False,
                "communication": [
                    {
                        "language": {
                            "coding": [
                                {
                                    "system": "urn:ietf:bcp:47",
                                    "code": "en-US",
                                    "display": "English",
                                }
                            ],
                            "text": "English",
                        }
                    }
                ],
            },
            "search": {"mode": "match"},
        },
    ],
}


patient_detail = {
    "resourceType": "Patient",
    "id": "4172",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2022-10-26T17:59:39.534+00:00",
        "source": "#U8mp7UmXjSsTPwER",
        "profile": ["http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"],
    },
    "text": {
        "status": "generated",
        "div": '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: a4e5a1a\n .   Person seed: -2041434765497594412  Population seed: 12345</div>',
    },
    "extension": [
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2106-3",
                        "display": "White",
                    },
                },
                {"url": "text", "valueString": "White"},
            ],
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2186-5",
                        "display": "Not Hispanic or Latino",
                    },
                },
                {"url": "text", "valueString": "Not Hispanic or Latino"},
            ],
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString": "Earlie274 Barton704",
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
            "valueCode": "M",
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueAddress": {
                "city": "Marshfield",
                "state": "Massachusetts",
                "country": "US",
            },
        },
        {
            "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
            "valueDecimal": 0.0,
        },
        {
            "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
            "valueDecimal": 9.0,
        },
    ],
    "identifier": [
        {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "f6aae6ae-c382-593c-1330-6d6598282031",
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR",
                        "display": "Medical Record Number",
                    }
                ],
                "text": "Medical Record Number",
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "f6aae6ae-c382-593c-1330-6d6598282031",
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "SS",
                        "display": "Social Security Number",
                    }
                ],
                "text": "Social Security Number",
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "999-56-1370",
        },
    ],
    "name": [
        {"use": "official", "family": "Dickinson688", "given": ["Brock407", "Bret7"]}
    ],
    "telecom": [{"system": "phone", "value": "555-385-9019", "use": "home"}],
    "gender": "male",
    "birthDate": "2012-06-10",
    "address": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                    "extension": [
                        {"url": "latitude", "valueDecimal": 42.459178010105404},
                        {"url": "longitude", "valueDecimal": -71.20555483378946},
                    ],
                }
            ],
            "line": ["370 Auer Knoll"],
            "city": "Arlington",
            "state": "MA",
            "postalCode": "02476",
            "country": "US",
        }
    ],
    "maritalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                "code": "S",
                "display": "Never Married",
            }
        ],
        "text": "Never Married",
    },
    "multipleBirthBoolean": False,
    "communication": [
        {
            "language": {
                "coding": [
                    {"system": "urn:ietf:bcp:47", "code": "en-US", "display": "English"}
                ],
                "text": "English",
            }
        }
    ],
}

all_patients_response = json.dumps(all_patients)
patient_detail_response = json.dumps(patient_detail)
