pipelines:
  pull-requests:
    '**':
      - parallel:
        - step:
            name: Linter (using Flake8)
            image: python:3.9
            script:
              - pip install flake8
              - flake8 --config=central_database/setup.cfg
        - step:
            name: Django automated tests and coverage (using pytest)
            image: python:3.9
            script:
              - pip install poetry==1.4.2
              - pip install virtualenv
              - poetry config virtualenvs.in-project false
              - poetry config virtualenvs.create false
              - poetry install --no-interaction --no-root
              - export DATABASE_URL=postgres://debug:debug@127.0.0.0:5432/central_database
              - export POSTGRES_HOST=127.0.0.0
              - export POSTGRES_PORT=5432
              - export POSTGRES_DB=central_database
              - export POSTGRES_USER=debug
              - export POSTGRES_PASSWORD=debug
              - export USE_DOCKER=no
              - export DJANGO_SETTINGS_MODULE=config.settings.pipeline_test
              - apt-get update && apt-get install -y binutils libproj-dev gdal-bin
              - python central_database/manage.py migrate
              - pytest --cov --cov-fail-under=80 central_database/
            services:
              - postgres
definitions:
  services:
    postgres:
      image: postgis/postgis:14-3.1
      variables:
        POSTGRES_HOST: "127.0.0.0"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: central_database
        POSTGRES_USER: debug
        POSTGRES_PASSWORD: debug
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
