steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'VITE_MODE=$BRANCH_NAME', '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME-di-client-$BRANCH_NAME:$COMMIT_SHA', '-f', './frontend/Dockerfile.prod', './frontend']
- name: 'google/cloud-sdk:alpine'
  args:
    - source
    - repos
    - clone
    - $_HELM_CHART_REPOSITORY
  id: Clone Helm chart repository
  entrypoint: gcloud
- name: 'google/cloud-sdk:alpine'
  args:
    - '-c'
    - >
      cd $_HELM_CHART_REPOSITORY

      git checkout master

      cd di-client

      if [ "$BRANCH_NAME" = "master" ];
      then
        sed -i "s/tag: [a-z0-9]\{40\}/tag: ${COMMIT_SHA}/" values-master.yaml
      else
        sed -i "s/tag: [a-z0-9]\{40\}/tag: ${COMMIT_SHA}/" values-$BRANCH_NAME.yaml
      fi

      git config --global user.email
      "cloudbuild@ptm-devops.portaltelemedicina.com.br"

      git config --global user.name "CloudBuild"

      git commit -am "Update image tag"

      git push -o nokeycheck 
  id: Replace image tag and commit
  entrypoint: /bin/sh
images:
  - 'us.gcr.io/$PROJECT_ID/$REPO_NAME-di-client-$BRANCH_NAME:$COMMIT_SHA'
substitutions:
  _HELM_CHART_REPOSITORY: unicef-helm-charts
