apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-database-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-database-django
  template:
    metadata:
      labels:
        app: central-database-django
    spec:
      containers:
        - env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: POSTGRES_PORT
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:

                name: central-database-env
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: POSTGRES_PASSWORD
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: DATABASE_URL
          - name: USE_DOCKER
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: USE_DOCKER
          - name: DJANGO_SUPERUSER_USERNAME
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: DJANGO_SUPERUSER_USERNAME
          - name: DJANGO_SUPERUSER_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: DJANGO_SUPERUSER_PASSWORD
          - name: DJANGO_SUPERUSER_EMAIL
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: DJANGO_SUPERUSER_EMAIL
          - name: IPYTHONDIR
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: IPYTHONDIR
          - name: DJANGO_SETTINGS_MODULE
            valueFrom:
              configMapKeyRef:
                name: central-database-env
                key: DJANGO_SETTINGS_MODULE
          name: central-database-django
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: localhost
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: localhost
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          image: us-central1-docker.pkg.dev/fiery-synthesis-359714/central-database/central-database-django@sha256:8cdf89fef4602a42ec2f7b4f91fd1c7c471bea3a66d319db0d87344be22b3ccc
          ports:
          - containerPort: 8000
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 200Mi
      terminationGracePeriodSeconds: 60
