#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



python manage.py flush --no-input
python manage.py migrate
python manage.py loaddata central_database/vaccines/fixtures/*.json
python manage.py createsuperuser --noinput

python -m debugpy --listen 0.0.0.0:5678 -m uvicorn config.asgi:application --reload --host 0.0.0.0 --port 8000
