apiVersion: apps/v1
kind: Deployment
metadata:
  name: hapi-fhir-jpaserver-start
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hapi-fhir-jpaserver-start
  template:
    metadata:
      labels:
        app : hapi-fhir-jpaserver-start
    spec:
      containers:
        - env:
          - name: hapi.fhir.mdm_enabled
            valueFrom:
              configMapKeyRef:
                name: hapifhir-env
                key: hapi.fhir.mdm_enabled
          - name: spring.datasource.url
            valueFrom:
              configMapKeyRef:
                name: hapifhir-env
                key: spring.datasource.url
          - name: spring.datasource.username
            valueFrom:
              configMapKeyRef:
                name: hapifhir-env
                key: spring.datasource.username
          - name: spring.datasource.password
            valueFrom:
              configMapKeyRef:
                name: hapifhir-env
                key: spring.datasource.password
          - name: spring.datasource.driverClassName
            valueFrom:
              configMapKeyRef:
                name: hapifhir-env
                key: spring.datasource.driverClassName
          - name: spring.jpa.properties.hibernate.dialect
            valueFrom:
              configMapKeyRef:
                name: hapifhir-env
                key: spring.jpa.properties.hibernate.dialect
          name: hapi-fhir-jpaserver-start
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /fhir/metadata
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /fhir/metadata
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          image: hapiproject/hapi:v6.0.1
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 3Gi
            requests:
              cpu: 1000m
              memory: 2Gi
      terminationGracePeriodSeconds: 60
