# Generated by Django 3.2.14 on 2022-12-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_auto_20221117_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinealert',
            name='patient_id',
            field=models.CharField(help_text='Patient ID from FHIR.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vaccinestatus',
            name='patient_id',
            field=models.CharField(help_text='Patient ID from FHIR.', max_length=255),
        ),
    ]
