# Generated by Django 3.2.14 on 2023-01-10 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccines', '0003_auto_20221230_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVaccineStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Patient ID from FHIR.', max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vaccine_dose', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vaccines.vaccinedose')),
            ],
            options={
                'verbose_name': 'historical vaccine status',
                'verbose_name_plural': 'historical vaccine statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVaccineDose',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('minimum_recommended_age', models.PositiveIntegerField(blank=True, default=None, help_text='The minimum age, in months, if the administration can be performed within a range. If there is no range, leave it blank and use only the maximum recommended age.', null=True)),
                ('maximum_recommended_age', models.PositiveIntegerField(help_text='The maximum age, in months, if the administration can be performed within a range. If there is no range, this is the recommended age.')),
                ('dose_order', models.PositiveSmallIntegerField(help_text='The order of this dose in the vaccination schedule.')),
                ('booster', models.BooleanField(help_text='Check if this is considered a booster shot in the vaccination schedule.')),
                ('gender_recommendation', models.CharField(choices=[('B', 'Both'), ('M', 'Male'), ('F', 'Female')], default='B', help_text='Select if this dose is gender specific.', max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vaccines.vaccine')),
            ],
            options={
                'verbose_name': 'historical vaccine dose',
                'verbose_name_plural': 'historical vaccine doses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVaccineAlertType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(help_text='Describe the event/issue this alert is representing.', max_length=100)),
                ('description_en', models.CharField(help_text='Describe the event/issue this alert is representing.', max_length=100, null=True)),
                ('description_pt_br', models.CharField(help_text='Describe the event/issue this alert is representing.', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vaccine alert type',
                'verbose_name_plural': 'historical vaccine alert types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVaccineAlert',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Patient ID from FHIR.', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True, help_text='Check if this alert is active.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alert_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vaccines.vaccinealerttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vaccine_dose', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vaccines.vaccinedose')),
            ],
            options={
                'verbose_name': 'historical vaccine alert',
                'verbose_name_plural': 'historical vaccine alerts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVaccine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('system', models.CharField(choices=[('CVX', 'http://hl7.org/fhir/sid/cvx'), ('BRI', 'https://integracao.esusab.ufsc.br/ledi/documentacao/referencias/dicionario.html#imunobiologico')], help_text='Which system of codes is used on FHIR to define the vaccine codes.', max_length=3)),
                ('code', models.PositiveSmallIntegerField(help_text='Vaccine code used defined on a specific system.')),
                ('display', models.CharField(help_text='Small text description from display field on FHIR.', max_length=200)),
                ('description', models.CharField(help_text='Full text description of the vaccine.', max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vaccine',
                'verbose_name_plural': 'historical vaccines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
