# Generated by Django 3.2.14 on 2023-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0005_auto_20230216_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaccinestatus',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinestatus',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
