# Generated by Django 3.2.14 on 2023-03-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_historicalclient'),
        ('vaccines', '0005_auto_20230216_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaccinealert',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.client'),
        ),
        migrations.AddField(
            model_name='historicalvaccinestatus',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.client'),
        ),
        migrations.AddField(
            model_name='vaccinealert',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinestatus',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
            preserve_default=False,
        ),
    ]
