# Generated by Django 3.2.14 on 2023-03-22 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20230322_1410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccines', '0005_auto_20230216_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVaccineProtocolClient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical vaccine protocol client',
                'verbose_name_plural': 'historical vaccine protocol clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VaccineProtocolClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='vaccineprotocol',
            name='vaccines_va_name_b5701e_idx',
        ),
        migrations.RemoveField(
            model_name='vaccineprotocol',
            name='name',
        ),
        migrations.AddField(
            model_name='vaccineprotocol',
            name='protocol_type',
            field=models.CharField(choices=[('Previne', 'Previne')], default='Previne', max_length=255),
        ),
        migrations.AddIndex(
            model_name='vaccineprotocol',
            index=models.Index(fields=['protocol_type'], name='vaccines_va_protoco_44ef9e_idx'),
        ),
        migrations.AddField(
            model_name='vaccineprotocolclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.client'),
        ),
        migrations.AddField(
            model_name='vaccineprotocolclient',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccines.vaccineprotocol'),
        ),
        migrations.AddField(
            model_name='historicalvaccineprotocolclient',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.client'),
        ),
        migrations.AddField(
            model_name='historicalvaccineprotocolclient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvaccineprotocolclient',
            name='protocol',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vaccines.vaccineprotocol'),
        ),
    ]
