# Generated by Django 3.2.14 on 2023-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0006_auto_20230322_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvaccineprotocolclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalvaccineprotocolclient',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvaccineprotocolclient',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='vaccineprotocolclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='vaccineprotocolclient',
            name='protocol',
        ),
        migrations.RemoveIndex(
            model_name='vaccineprotocol',
            name='vaccines_va_protoco_44ef9e_idx',
        ),
        migrations.RemoveField(
            model_name='vaccineprotocol',
            name='protocol_type',
        ),
        migrations.AddField(
            model_name='vaccineprotocol',
            name='name',
            field=models.CharField(default='test_name', help_text='Protocol Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='vaccineprotocol',
            index=models.Index(fields=['name'], name='vaccines_va_name_b5701e_idx'),
        ),
        migrations.DeleteModel(
            name='HistoricalVaccineProtocolClient',
        ),
        migrations.DeleteModel(
            name='VaccineProtocolClient',
        ),
    ]
