# Generated by Django 3.2.14 on 2023-06-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_healthprofessional_historicalhealthprofessional'),
        ('vaccines', '0006_auto_20230605_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaccinestatus',
            name='batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalvaccinestatus',
            name='health_professional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.healthprofessional'),
        ),
        migrations.AddField(
            model_name='historicalvaccinestatus',
            name='next_dose_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinestatus',
            name='batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaccinestatus',
            name='health_professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.healthprofessional'),
        ),
        migrations.AddField(
            model_name='vaccinestatus',
            name='next_dose_application_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
