# Generated by Django 3.2.14 on 2023-06-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0007_auto_20230615_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvaccinealert',
            old_name='fhir_store_id',
            new_name='fhir_store',
        ),
        migrations.RenameField(
            model_name='historicalvaccinestatus',
            old_name='fhir_store_id',
            new_name='fhir_store',
        ),
        migrations.RenameField(
            model_name='vaccinealert',
            old_name='fhir_store_id',
            new_name='fhir_store',
        ),
        migrations.RenameField(
            model_name='vaccinestatus',
            old_name='fhir_store_id',
            new_name='fhir_store',
        ),
    ]
