# Generated by Django 3.2.14 on 2023-06-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0009_auto_20230616_0322'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vaccinestatus',
            constraint=models.UniqueConstraint(fields=('vaccine_dose', 'patient_id'), name='unique_vaccine_dose_per_patient'),
        ),
    ]
