# Generated by Django 3.2.14 on 2022-09-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('social_name', models.CharField(blank=True, default='', max_length=200)),
                ('date_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('', ''), ('M', 'Male'), ('F', 'Female')], default='', help_text='M - Male | F - Female', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_date', models.DateField()),
                ('name_of_vaccine', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.vaccines')),
            ],
        ),
    ]
