# Generated by Django 3.2.14 on 2023-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_patient', 'Can view patient'), ('add_patient', 'Can add patient'), ('change_patient', 'Can change patient'), ('delete_patient', 'Can delete patient')],
                'managed': False,
            },
        ),
    ]
