# Generated by Django 3.2.14 on 2023-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_historicalclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='test_city', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='city',
            field=models.CharField(default='test_city', max_length=255, null=True),
        ),
    ]
