# Generated by Django 3.2.14 on 2023-05-24 23:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20230524_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='micro_regions', to='customers.client')),
            ],
        ),
    ]
