# Generated by Django 3.2.14 on 2023-04-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20230322_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='children_born_alive',
        ),
        migrations.RemoveField(
            model_name='client',
            name='children_registered_in_APS',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ibge_population',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sisab_municipal_registration',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='children_born_alive',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='children_registered_in_APS',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='ibge_population',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='sisab_municipal_registration',
        ),
    ]
