# Generated by Django 3.2.14 on 2023-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20230509_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(default='test_city', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='city',
            field=models.CharField(default='test_city', max_length=255, null=True),
        ),
    ]
