# Generated by Django 3.2.14 on 2023-04-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20230403_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='children_born_alive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='children_registered_in_APS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Prefecture', 'Prefecture')], default='Prefecture', help_text='Select the type of client ', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='ibge_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sisab_municipal_registration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='children_born_alive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='children_registered_in_APS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='client_type',
            field=models.CharField(choices=[('Prefecture', 'Prefecture')], default='Prefecture', help_text='Select the type of client ', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='ibge_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='sisab_municipal_registration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
