# Generated by Django 3.2.14 on 2023-06-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_healthprofessional_historicalhealthprofessional'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='healthprofessional',
            index=models.Index(fields=['cns_number'], name='customers_h_cns_num_522492_idx'),
        ),
    ]
