# Generated by Django 3.2.14 on 2023-06-16 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_healthprofessional_customers_h_cns_num_522492_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='dataset_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='fhir_store_id',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='dataset_id',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='fhir_store_id',
        ),
        migrations.CreateModel(
            name='FhirStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_store_id', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='fhir_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.fhirstore'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='fhir_store',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.fhirstore'),
        ),
    ]
