version: 2




build:
  image: testing

python:
  version: 3.9
  
jobs:
   post_create_enviroment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with docs
sphinx:
  configuration: docs/conf.py
  
  

