version: '3'

volumes:
  central_database_local_postgres_data: {}
  central_database_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: central_database_local_django
    container_name: central_database_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: central_database_production_postgres
    container_name: central_database_local_postgres
    volumes:
      - central_database_local_postgres_data:/var/lib/postgresql/data:Z
      - central_database_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: central_database_local_docs
    container_name: central_database_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./central_database:/app/central_database:z
    ports:
      - "9000:9000"
    command: /start-docs

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: central_database_local_node
    container_name: central_database_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"

  fhir-server:
    build:
      context: ../fhir_server
      dockerfile: ./Dockerfile
    image: fhir_server
    container_name: fhir_server
    ports:
      - 3005:3000
