version: '3.8'

volumes:
  central_database_local_postgres_data: {}
  central_database_local_postgres_data_backups: {}
  hapifhir_local_postgres_data: {}

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.9-bullseye
        NODE_VERSION: "none"
    depends_on:
      - postgres
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    env_file:
      - ../central_database/.envs/.local/.postgres

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  django:
    build:
      context: ..
      dockerfile: ./central_database/compose/local/django/Dockerfile
    image: central_database_local_django
    container_name: central_database_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - ../central_database:/app:z
    env_file:
      - ../central_database/.envs/.local/.django
      - ../central_database/.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  unicef-front:
    build:
      context: ../unicef-front
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  postgres:
    build:
      context: ../central_database
      dockerfile: ./compose/production/postgres/Dockerfile
    image: central_database_production_postgres
    container_name: central_database_local_postgres
    volumes:
      - central_database_local_postgres_data:/var/lib/postgresql/data:Z
      - central_database_local_postgres_data_backups:/backups:z
    env_file:
      - ../central_database/.envs/.local/.postgres

  docs:
    image: central_database_local_docs
    container_name: central_database_local_docs
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: ./central_database/compose/local/docs/Dockerfile
    env_file:
      - ../central_database/.envs/.local/.django
    volumes:
      - ../central_database/docs:/docs:z
      - ../central_database/config:/app/config:z
      - ../central_database/central_database:/app/central_database:z
    ports:
      - "9000:9000"
    command: /start-docs

  hapifhir:
    image: hapiproject/hapi:v6.0.1
    container_name: hapi-fhir-jpaserver-start
    depends_on:
      - hapifhir-postgres
    env_file:
      - ../hapifhir/.envs/.local/.hapifhir
    ports:
      - "8080:8080"

  hapifhir-postgres:
    image: postgres:14
    restart: always
    volumes:
      - hapifhir_local_postgres_data:/var/lib/postgresql/data:Z
    expose:
    - "5434"
    env_file:
      - ../hapifhir/.envs/.local/.postgres
    command: -p 5434

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
