FROM node:14.20-alpine as build-stage

ARG VITE_MODE
ENV VITE_MODE=$VITE_MODE

WORKDIR /app

COPY ./package.json /app
COPY ./package-lock.json /app

COPY . .

RUN npm install


RUN npm run build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
