# Generated by Django 3.2.14 on 2022-11-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField(help_text='Patient ID from FHIR.')),
                ('completed', models.BooleanField(default=False)),
                ('vaccine_dose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccinedose')),
            ],
        ),
        migrations.AddIndex(
            model_name='vaccinestatus',
            index=models.Index(fields=['patient_id'], name='vaccines_va_patient_6728b8_idx'),
        ),
    ]
