# Generated by Django 3.2.14 on 2024-09-14 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0007_auto_20230616_0259'),
        ('vaccines', '0011_historicalvaccinationcard_vaccinationcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImmunization',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('entered-in-error', 'Entered in Error'), ('not-done', 'Not Done')], max_length=20)),
                ('occurrence_date', models.DateTimeField()),
                ('primary_source', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical immunization',
                'verbose_name_plural': 'historical immunizations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalImmunizationAlertSilence',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('silenced_at', models.DateTimeField(blank=True, editable=False)),
                ('reason', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical immunization alert silence',
                'verbose_name_plural': 'historical immunization alert silences',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalImmunizationRecommendation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Patient ID from FHIR', max_length=255)),
                ('date', models.DateTimeField()),
                ('forecast_status', models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('immune', 'Immune'), ('contraindicated', 'Contraindicated'), ('complete', 'Complete')], max_length=20)),
                ('forecast_reason', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical immunization recommendation',
                'verbose_name_plural': 'historical immunization recommendations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVaccineProtocol',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Protocol Name', max_length=255)),
                ('description', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical vaccine protocol',
                'verbose_name_plural': 'historical vaccine protocols',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('entered-in-error', 'Entered in Error'), ('not-done', 'Not Done')], max_length=20)),
                ('occurrence_date', models.DateTimeField()),
                ('primary_source', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImmunizationAlertSilence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silenced_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImmunizationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Patient ID from FHIR', max_length=255)),
                ('date', models.DateTimeField()),
                ('forecast_status', models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('immune', 'Immune'), ('contraindicated', 'Contraindicated'), ('complete', 'Complete')], max_length=20)),
                ('forecast_reason', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicalvaccinealert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='historicalvaccinealert',
            name='fhir_store',
        ),
        migrations.RemoveField(
            model_name='historicalvaccinealert',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvaccinealert',
            name='vaccine_dose',
        ),
        migrations.RemoveField(
            model_name='historicalvaccinealerttype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvaccinestatus',
            name='fhir_store',
        ),
        migrations.RemoveField(
            model_name='historicalvaccinestatus',
            name='health_professional',
        ),
        migrations.RemoveField(
            model_name='historicalvaccinestatus',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvaccinestatus',
            name='vaccine_dose',
        ),
        migrations.RemoveField(
            model_name='vaccinealert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='vaccinealert',
            name='fhir_store',
        ),
        migrations.RemoveField(
            model_name='vaccinealert',
            name='vaccine_dose',
        ),
        migrations.RemoveField(
            model_name='vaccinestatus',
            name='fhir_store',
        ),
        migrations.RemoveField(
            model_name='vaccinestatus',
            name='health_professional',
        ),
        migrations.RemoveField(
            model_name='vaccinestatus',
            name='vaccine_dose',
        ),
        migrations.RemoveConstraint(
            model_name='vaccine',
            name='unique_system_code',
        ),
        migrations.RemoveConstraint(
            model_name='vaccinedose',
            name='age_max_greater_age_min',
        ),
        migrations.RemoveConstraint(
            model_name='vaccinedose',
            name='unique_vaccine_dose_order_gender_recommendation',
        ),
        migrations.RemoveIndex(
            model_name='vaccine',
            name='vaccines_va_system_ed9718_idx',
        ),
        migrations.RemoveIndex(
            model_name='vaccine',
            name='vaccines_va_code_8089a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='vaccinedose',
            name='vaccines_va_vaccine_aa69bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='vaccinedose',
            name='vaccines_va_maximum_b6fbd2_idx',
        ),
        migrations.RemoveField(
            model_name='historicalvaccinationcard',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalvaccine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vaccinationcard',
            name='client',
        ),
        migrations.AlterField(
            model_name='historicalvaccinationcard',
            name='patient_id',
            field=models.CharField(help_text='Patient ID from FHIR', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalvaccine',
            name='code',
            field=models.CharField(help_text='Vaccine code', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalvaccine',
            name='display',
            field=models.CharField(help_text='Display name for the vaccine', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalvaccine',
            name='system',
            field=models.CharField(help_text='Coding system for the vaccine code', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalvaccinedose',
            name='booster',
            field=models.BooleanField(help_text='Whether this is a booster dose'),
        ),
        migrations.AlterField(
            model_name='historicalvaccinedose',
            name='dose_order',
            field=models.PositiveSmallIntegerField(help_text='The order of this dose in the vaccination schedule'),
        ),
        migrations.AlterField(
            model_name='historicalvaccinedose',
            name='gender_recommendation',
            field=models.CharField(choices=[('B', 'Both'), ('M', 'Male'), ('F', 'Female')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalvaccinedose',
            name='maximum_recommended_age',
            field=models.PositiveIntegerField(help_text='Maximum recommended age in months'),
        ),
        migrations.AlterField(
            model_name='historicalvaccinedose',
            name='minimum_recommended_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum recommended age in months', null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcard',
            name='patient_id',
            field=models.CharField(help_text='Patient ID from FHIR', max_length=255),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='code',
            field=models.CharField(help_text='Vaccine code', max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='display',
            field=models.CharField(help_text='Display name for the vaccine', max_length=255),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='system',
            field=models.CharField(help_text='Coding system for the vaccine code', max_length=255),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='booster',
            field=models.BooleanField(help_text='Whether this is a booster dose'),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='dose_order',
            field=models.PositiveSmallIntegerField(help_text='The order of this dose in the vaccination schedule'),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='gender_recommendation',
            field=models.CharField(choices=[('B', 'Both'), ('M', 'Male'), ('F', 'Female')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='maximum_recommended_age',
            field=models.PositiveIntegerField(help_text='Maximum recommended age in months'),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='minimum_recommended_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum recommended age in months', null=True),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='vaccines.vaccine'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together={('system', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='vaccinedose',
            unique_together={('vaccine', 'dose_order', 'gender_recommendation')},
        ),
        migrations.DeleteModel(
            name='HistoricalVaccineAlert',
        ),
        migrations.DeleteModel(
            name='HistoricalVaccineAlertType',
        ),
        migrations.DeleteModel(
            name='HistoricalVaccineStatus',
        ),
        migrations.DeleteModel(
            name='VaccineAlert',
        ),
        migrations.DeleteModel(
            name='VaccineAlertType',
        ),
        migrations.DeleteModel(
            name='VaccineStatus',
        ),
        migrations.AddField(
            model_name='immunizationrecommendation',
            name='fhir_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.fhirstore'),
        ),
        migrations.AddField(
            model_name='immunizationrecommendation',
            name='vaccine_dose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccines.vaccinedose'),
        ),
        migrations.AddField(
            model_name='immunizationalertsilence',
            name='immunization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.immunization'),
        ),
        migrations.AddField(
            model_name='immunizationalertsilence',
            name='silenced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immunization',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.healthprofessional'),
        ),
        migrations.AddField(
            model_name='immunization',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immunizations', to='vaccines.immunizationrecommendation'),
        ),
        migrations.AddField(
            model_name='historicalvaccineprotocol',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.client'),
        ),
        migrations.AddField(
            model_name='historicalvaccineprotocol',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimmunizationrecommendation',
            name='fhir_store',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.fhirstore'),
        ),
        migrations.AddField(
            model_name='historicalimmunizationrecommendation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimmunizationrecommendation',
            name='vaccine_dose',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vaccines.vaccinedose'),
        ),
        migrations.AddField(
            model_name='historicalimmunizationalertsilence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimmunizationalertsilence',
            name='immunization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vaccines.immunization'),
        ),
        migrations.AddField(
            model_name='historicalimmunizationalertsilence',
            name='silenced_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimmunization',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimmunization',
            name='performer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.healthprofessional'),
        ),
        migrations.AddField(
            model_name='historicalimmunization',
            name='recommendation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vaccines.immunizationrecommendation'),
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='description',
        ),
    ]
