# Generated by Django 3.2.14 on 2024-09-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0012_auto_20240914_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaccine',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the vaccine', null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the vaccine', null=True),
        ),
    ]
