# Generated by Django 3.2.14 on 2024-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0013_auto_20240914_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimmunization',
            name='occurrence_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='occurrence_date',
            field=models.DateField(),
        ),
    ]
