# Generated by Django 3.2.14 on 2024-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0014_auto_20240915_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimmunizationrecommendation',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalimmunizationrecommendation',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalimmunizationrecommendation',
            name='forecast_status',
            field=models.CharField(blank=True, choices=[('due', 'Due'), ('overdue', 'Overdue'), ('immune', 'Immune'), ('contraindicated', 'Contraindicated'), ('complete', 'Complete')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvaccinedose',
            name='booster',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this is a booster dose', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvaccinedose',
            name='maximum_recommended_age',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum recommended age in months', null=True),
        ),
        migrations.AlterField(
            model_name='immunizationrecommendation',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunizationrecommendation',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunizationrecommendation',
            name='forecast_status',
            field=models.CharField(blank=True, choices=[('due', 'Due'), ('overdue', 'Overdue'), ('immune', 'Immune'), ('contraindicated', 'Contraindicated'), ('complete', 'Complete')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='booster',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this is a booster dose', null=True),
        ),
        migrations.AlterField(
            model_name='vaccinedose',
            name='maximum_recommended_age',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum recommended age in months', null=True),
        ),
    ]
