# Generated by Django 3.2.14 on 2024-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0015_auto_20240915_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimmunizationrecommendation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalimmunizationrecommendation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunizationrecommendation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunizationrecommendation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
